// Next.js Route Handler paths (called by client components via clientApi, baseURL "/api")
export const ENDPOINTS = {
  auth: {
    login:          "/auth/login",
    logout:         "/auth/logout",
    me:             "/auth/me",
    accountSetup:   "/auth/account-setup",
    forgotPassword: "/auth/forgot-password",
    verifyOtp:      "/auth/verify-otp",
    resetPassword:  "/auth/reset-password",
    changePassword: "/auth/change-password",
  },
  users: {
    list:        "/users",
    create:      "/users",
    byId:        (id: string) => `/users/${id}`,
    detail:      (id: string) => `/users/${id}/detail`,
    resendSetup: (id: string) => `/users/${id}/resend-setup`,
    photo:       (id: string) => `/users/${id}/photo`,
    myPhoto:     "/users/me/photo",
    documents:   (id: string) => `/users/${id}/documents`,
  },
  documents: {
    byId:   (id: string) => `/documents/${id}`,
    verify: (id: string) => `/documents/${id}/verify`,
    file:   (id: string) => `/documents/${id}/file`,
  },
  companies: {
    list:   "/companies",
    create: "/companies",
    byId:   (id: string) => `/companies/${id}`,
  },
  clientCompanies: {
    list:   "/client-companies",
    create: "/client-companies",
    byId:   (id: string) => `/client-companies/${id}`,
  },
  clients: {
    list:   "/clients",
    create: "/clients",
    byId:   (id: string) => `/clients/${id}`,
  },
  sites: {
    list:   "/sites",
    create: "/sites",
    clientPortal: "/sites/client-portal",
    byId:   (id: string) => `/sites/${id}`,
    supervisors: (id: string) => `/sites/${id}/supervisors`,
    cleaners:    (id: string) => `/sites/${id}/cleaners`,
    cleanerProfiles: (id: string) => `/sites/${id}/cleaner-profiles`,
    addCleanerProfile: (id: string) => `/sites/${id}/cleaner-profiles/add`,
    removeCleanerProfile: (id: string, profileId: string) => `/sites/${id}/cleaner-profiles/${profileId}`,
    supervisorProfiles: (id: string) => `/sites/${id}/supervisor-profiles`,
    addSupervisorProfile: (id: string) => `/sites/${id}/supervisor-profiles/add`,
    removeSupervisorProfile: (id: string, profileId: string) => `/sites/${id}/supervisor-profiles/${profileId}`,
    cleaningTemplates: (id: string) => `/sites/${id}/cleaning-templates`,
    cleaningCheckIn: (id: string) => `/sites/${id}/cleaning-schedule/check-in`,
    eligibleCleaners: (id: string) => `/sites/${id}/eligible-cleaners`,
    eligibleSupervisors: (id: string) => `/sites/${id}/eligible-supervisors`,
    shifts: (id: string) => `/sites/${id}/shifts`,
  },
  shifts: {
    byId:    (id: string) => `/shifts/${id}`,
    default: (id: string) => `/shifts/${id}/default`,
  },
  outsourceProjects: {
    list:   "/outsource-projects",
    create: "/outsource-projects",
    byId:   (id: string) => `/outsource-projects/${id}`,
  },
  floors: {
    list:   "/floors",
    create: "/floors",
    byId:   (id: string) => `/floors/${id}`,
  },
  areas: {
    list:   "/areas",
    create: "/areas",
    byId:   (id: string) => `/areas/${id}`,
  },
  cleaners: {
    list: "/cleaners",
    byId: (id: string) => `/cleaners/${id}`,
    detail: (id: string) => `/cleaners/${id}/detail`,
    detailByUser: (userId: string) => `/cleaners/by-user/${userId}/detail`,
  },
  attendance: {
    mySites:  "/attendance/my-sites",
    checkIn:  "/attendance/check-in",
    checkOut: "/attendance/check-out",
    heartbeat: "/attendance/heartbeat",
    logs:     "/attendance",
    me:       "/attendance/me",
  },
  tasks: {
    myOccurrences:   "/tasks/my-occurrences",
    complete:        "/tasks/complete",
    reviewComplete:  "/tasks/review-complete",
    inspect:         "/tasks/inspect",
    inspectComplete: "/tasks/inspect/complete",
    photo:           (id: string) => `/tasks/completions/photos/${id}`,
  },
  assignments: {
    create:      "/assignments",
    occurrences: "/assignments/occurrences",
    stats:       "/assignments/stats",
    taskNames:   "/assignments/task-names",
    byId:        (id: string) => `/assignments/${id}`,
    occurrence:  (taskId: string, date: string) => `/assignments/tasks/${taskId}/occurrences/${date}`,
    occurrenceContent: (taskId: string, date: string) =>
      `/assignments/tasks/${taskId}/occurrences/${date}/content`,
  },
  assignmentDrafts: {
    list:   "/assignment-drafts",
    create: "/assignment-drafts",
    byId:   (id: string) => `/assignment-drafts/${id}`,
  },
  taskTemplates: {
    list:   "/task-templates",
    create: "/task-templates",
    byId:   (id: string) => `/task-templates/${id}`,
  },
  inventory: {
    items:        "/inventory/items",
    itemById:     (id: string) => `/inventory/items/${id}`,
    itemStock:    (id: string) => `/inventory/items/${id}/stock`,
    siteInventory: (siteId: string) => `/inventory/sites/${siteId}`,
    siteAdjust:   (siteId: string) => `/inventory/sites/${siteId}/adjust`,
    lowStock:     "/inventory/low-stock",
    transactions: "/inventory/transactions",
    requests:     "/inventory/requests",
    requestById:  (id: string) => `/inventory/requests/${id}`,
    requestAction: (id: string, action: string) => `/inventory/requests/${id}/${action}`,
    deliveries:   "/inventory/deliveries",
    deliveryById: (id: string) => `/inventory/deliveries/${id}`,
    deliveryAction: (id: string, action: string) => `/inventory/deliveries/${id}/${action}`,
    cleanerInventoryMine: "/inventory/cleaners/me",
    cleanerInventory: (cleanerId: string) => `/inventory/cleaners/${cleanerId}`,
    stats:        "/inventory/stats",
    itemBatches:  (id: string) => `/inventory/items/${id}/batches`,
  },
  suppliers: {
    list:   "/suppliers",
    create: "/suppliers",
    byId:   (id: string) => `/suppliers/${id}`,
  },
  purchaseOrders: {
    list:   "/purchase-orders",
    create: "/purchase-orders",
    byId:   (id: string) => `/purchase-orders/${id}`,
    cancel: (id: string) => `/purchase-orders/${id}/cancel`,
  },
  goodsReceipts: {
    list:   "/goods-receipts",
    create: "/goods-receipts",
    byId:   (id: string) => `/goods-receipts/${id}`,
  },
  notifications: {
    list:        "/notifications",
    unreadCount: "/notifications/unread-count",
    read:        (id: string) => `/notifications/${id}/read`,
    readAll:     "/notifications/read-all",
  },
  roles: {
    list: "/roles",
  },
  dashboard: {
    overview: "/dashboard/overview",
  },
  // These have no Spring Boot backend to mirror — the Next.js route handler *is*
  // the backend. Consumed by client components via clientApi ("/api" baseURL).
  inspections: {
    list:         "/inspections",
    completeArea: (id: string) => `/inspections/areas/${id}/complete`,
  },
  complaints: {
    list:    "/complaints",
    create:  "/complaints",
    complete: (id: string) => `/complaints/${id}/complete`,
    resolve: (id: string) => `/complaints/${id}/resolve`,
    photo:   (id: string) => `/complaints/photos/${id}`,
  },
  contact: {
    submit: "/contact",
  },
} as const;

// Spring Boot backend paths (called server-side from Route Handlers)
export const BACKEND = {
  auth: {
    login:          "/api/v1/auth/login",
    me:             "/api/v1/auth/me",
    accountSetup:   "/api/v1/auth/account-setup",
    forgotPassword: "/api/v1/auth/forgot-password",
    verifyOtp:      "/api/v1/auth/verify-otp",
    resetPassword:  "/api/v1/auth/reset-password",
    changePassword: "/api/v1/auth/change-password",
  },
  users: {
    list:        "/api/v1/users",
    create:      "/api/v1/users",
    byId:        (id: string) => `/api/v1/users/${id}`,
    detail:      (id: string) => `/api/v1/users/${id}/detail`,
    resendSetup: (id: string) => `/api/v1/users/${id}/resend-setup`,
    photo:       (id: string) => `/api/v1/users/${id}/photo`,
    myPhoto:     "/api/v1/users/me/photo",
    documents:   (id: string) => `/api/v1/users/${id}/documents`,
  },
  documents: {
    byId:   (id: string) => `/api/v1/documents/${id}`,
    verify: (id: string) => `/api/v1/documents/${id}/verify`,
    file:   (id: string) => `/api/v1/documents/${id}/file`,
  },
  companies: {
    list:   "/api/v1/companies",
    create: "/api/v1/companies",
    byId:   (id: string) => `/api/v1/companies/${id}`,
  },
  clientCompanies: {
    list:   "/api/v1/client-companies",
    create: "/api/v1/client-companies",
    byId:   (id: string) => `/api/v1/client-companies/${id}`,
  },
  clients: {
    list:   "/api/v1/clients",
    create: "/api/v1/clients",
    byId:   (id: string) => `/api/v1/clients/${id}`,
    byCompany: (companyId: string) => `/api/v1/clients?clientCompanyId=${companyId}`,
  },
  sites: {
    list:   "/api/v1/sites",
    create: "/api/v1/sites",
    clientPortal: "/api/v1/sites/client-portal",
    byId:   (id: string) => `/api/v1/sites/${id}`,
    supervisors: (id: string) => `/api/v1/sites/${id}/supervisors`,
    cleaners:    (id: string) => `/api/v1/sites/${id}/cleaners`,
    cleanerProfiles: (id: string) => `/api/v1/sites/${id}/cleaner-profiles`,
    addCleanerProfile: (id: string) => `/api/v1/sites/${id}/cleaner-profiles/add`,
    removeCleanerProfile: (id: string, profileId: string) => `/api/v1/sites/${id}/cleaner-profiles/${profileId}`,
    supervisorProfiles: (id: string) => `/api/v1/sites/${id}/supervisor-profiles`,
    addSupervisorProfile: (id: string) => `/api/v1/sites/${id}/supervisor-profiles/add`,
    removeSupervisorProfile: (id: string, profileId: string) => `/api/v1/sites/${id}/supervisor-profiles/${profileId}`,
    cleaningTemplates: (id: string) => `/api/v1/sites/${id}/cleaning-templates`,
    cleaningCheckIn: (id: string) => `/api/v1/sites/${id}/cleaning-schedule/check-in`,
    eligibleCleaners: (id: string) => `/api/v1/sites/${id}/eligible-cleaners`,
    eligibleSupervisors: (id: string) => `/api/v1/sites/${id}/eligible-supervisors`,
    shifts: (id: string) => `/api/v1/sites/${id}/shifts`,
  },
  shifts: {
    byId:    (id: string) => `/api/v1/shifts/${id}`,
    default: (id: string) => `/api/v1/shifts/${id}/default`,
  },
  outsourceProjects: {
    list:   "/api/v1/outsource-projects",
    create: "/api/v1/outsource-projects",
    byId:   (id: string) => `/api/v1/outsource-projects/${id}`,
  },
  floors: {
    list:   "/api/v1/floors",
    create: "/api/v1/floors",
    byId:   (id: string) => `/api/v1/floors/${id}`,
  },
  areas: {
    list:   "/api/v1/areas",
    create: "/api/v1/areas",
    byId:   (id: string) => `/api/v1/areas/${id}`,
  },
  cleaners: {
    list: "/api/v1/cleaners",
    byId: (id: string) => `/api/v1/cleaners/${id}`,
    detail: (id: string) => `/api/v1/cleaners/${id}/detail`,
    detailByUser: (userId: string) => `/api/v1/cleaners/by-user/${userId}/detail`,
  },
  attendance: {
    mySites:  "/api/v1/attendance/my-sites",
    checkIn:  "/api/v1/attendance/check-in",
    checkOut: "/api/v1/attendance/check-out",
    heartbeat: "/api/v1/attendance/heartbeat",
    logs:     "/api/v1/attendance",
    me:       "/api/v1/attendance/me",
  },
  tasks: {
    myOccurrences:   "/api/v1/tasks/my-occurrences",
    complete:        "/api/v1/tasks/complete",
    reviewComplete:  "/api/v1/tasks/review-complete",
    inspect:         "/api/v1/tasks/inspect",
    inspectComplete: "/api/v1/tasks/inspect/complete",
    photo:           (id: string) => `/api/v1/tasks/completions/photos/${id}`,
  },
  assignments: {
    create:      "/api/v1/assignments",
    occurrences: "/api/v1/assignments/occurrences",
    stats:       "/api/v1/assignments/stats",
    taskNames:   "/api/v1/assignments/task-names",
    byId:        (id: string) => `/api/v1/assignments/${id}`,
    occurrence:  (taskId: string, date: string) => `/api/v1/assignments/tasks/${taskId}/occurrences/${date}`,
    occurrenceContent: (taskId: string, date: string) =>
      `/api/v1/assignments/tasks/${taskId}/occurrences/${date}/content`,
  },
  assignmentDrafts: {
    list:   "/api/v1/assignment-drafts",
    create: "/api/v1/assignment-drafts",
    byId:   (id: string) => `/api/v1/assignment-drafts/${id}`,
  },
  taskTemplates: {
    list:   "/api/v1/task-templates",
    create: "/api/v1/task-templates",
    byId:   (id: string) => `/api/v1/task-templates/${id}`,
  },
  inventory: {
    items:        "/api/v1/inventory/items",
    itemById:     (id: string) => `/api/v1/inventory/items/${id}`,
    itemStock:    (id: string) => `/api/v1/inventory/items/${id}/stock`,
    siteInventory: (siteId: string) => `/api/v1/inventory/sites/${siteId}`,
    siteAdjust:   (siteId: string) => `/api/v1/inventory/sites/${siteId}/adjust`,
    lowStock:     "/api/v1/inventory/low-stock",
    transactions: "/api/v1/inventory/transactions",
    requests:     "/api/v1/inventory/requests",
    requestById:  (id: string) => `/api/v1/inventory/requests/${id}`,
    requestAction: (id: string, action: string) => `/api/v1/inventory/requests/${id}/${action}`,
    deliveries:   "/api/v1/inventory/deliveries",
    deliveryById: (id: string) => `/api/v1/inventory/deliveries/${id}`,
    deliveryAction: (id: string, action: string) => `/api/v1/inventory/deliveries/${id}/${action}`,
    cleanerInventoryMine: "/api/v1/inventory/cleaners/me",
    cleanerInventory: (cleanerId: string) => `/api/v1/inventory/cleaners/${cleanerId}`,
    stats:        "/api/v1/inventory/stats",
    itemBatches:  (id: string) => `/api/v1/inventory/items/${id}/batches`,
  },
  suppliers: {
    list:   "/api/v1/suppliers",
    create: "/api/v1/suppliers",
    byId:   (id: string) => `/api/v1/suppliers/${id}`,
  },
  purchaseOrders: {
    list:   "/api/v1/purchase-orders",
    create: "/api/v1/purchase-orders",
    byId:   (id: string) => `/api/v1/purchase-orders/${id}`,
    cancel: (id: string) => `/api/v1/purchase-orders/${id}/cancel`,
  },
  goodsReceipts: {
    list:   "/api/v1/goods-receipts",
    create: "/api/v1/goods-receipts",
    byId:   (id: string) => `/api/v1/goods-receipts/${id}`,
  },
  notifications: {
    list:        "/api/v1/notifications",
    unreadCount: "/api/v1/notifications/unread-count",
    read:        (id: string) => `/api/v1/notifications/${id}/read`,
    readAll:     "/api/v1/notifications/read-all",
  },
  roles: {
    list: "/api/v1/roles",
  },
  dashboard: {
    overview: "/api/v1/dashboard/overview",
  },
  complaints: {
    list:    "/api/v1/complaints",
    create:  "/api/v1/complaints",
    complete: (id: string) => `/api/v1/complaints/${id}/complete`,
    resolve: (id: string) => `/api/v1/complaints/${id}/resolve`,
    photo:   (id: string) => `/api/v1/complaints/photos/${id}`,
  },
} as const;
